### ISSUE TITLE
View Booking Information: Name column displays item no.

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#599]
Steps to replicate:
1. Add a new LCL booking with sample items.
2. Go back to booking list.
3. Click the "View Booking Information" icon corresponding to the previously created booking.

Actual result: Name column displays item no. while on the booking form, item name was displayed
Expected result: Name column should display item names.

![screenshot-3](https://cloud.githubusercontent.com/assets/7791554/7806257/549cbd92-03b1-11e5-8863-fd91a217f2c9.png)

**Comment by knarceo** [comment]
Fixed on next push

**Comment by barbacenasmc** [comment]
Expected result is still not achieved because the "Name"  column displays item code instead of item name:

![image](https://cloud.githubusercontent.com/assets/7791554/7906938/33dc06cc-0865-11e5-8872-8e6d584befc7.png)

**Comment by ZaX09** [comment]
verified as fixed

**Comment by ZaX09** [comment]
issue still exists. Name column of cargo details still displays item code.

**Comment by knarceo** [comment]
Fixed on next push

**Comment by barbacenasmc** [comment]
Issue fix was already verified.
