### ISSUE TITLE
Add Customer Contact: List does not show contacts with "Bill To" and "Solicitor" contact types

### ISSUE THREAD

**Issue by barbacenasmc** [johnpelquingua/freightbit-logistics#624]
Steps to replicate:

1. Navigate to customer module.
2. Open an existing customer profile.
3. Go to contacts.
4. Add new contact with "Bill To" as contact type.
5. Add another contact with "Solicitor" as contact type.

Actual result: A success message was displayed but nothing was added to the list.
Expected result: A success message should display and the new contact person should be added to the list.

**Comment by emarino0411** [comment]
Fixed.

**Comment by egmsantos** [comment]
Issue still can be replicated.
![eios_626](https://cloud.githubusercontent.com/assets/12589800/9107416/a10e1f78-3c59-11e5-865c-1879706f7c01.png)
